/* Nederlandse vertalingen, per data-i18n-sleutel. Engels staat in index.html. */
export const nl: Record<string, string> = {
  'gate.sub': 'Een reis langs de eeuwige weg',
  'gate.sound': 'Binnengaan met geluid',
  'gate.silent': 'Binnengaan in stilte',
  'gate.loading': 'De tanpura wordt gestemd…',
  'gate.note': 'Geen afbeeldingen. Geen audiobestanden. Elke pixel en elke klank wordt live door code gegenereerd.',

  'om.sub': 'De eeuwige weg — zonder begin, zonder einde.',
  'om.g1': 'eeuwig, altijd bestaand, steeds vernieuwd',
  'om.g2': 'dat wat draagt — de orde die kosmos, samenleving en zelf in stand houdt',
  'om.cue': 'Scroll om de cyclus te beginnen',

  'nada.title': 'De wereld is klank',
  'nada.lede': 'Om — deze lettergreep is dit alles. Alles wat was, is en zal zijn, is Om; en wat voorbij de drie tijden ligt, ook dat is Om. <cite>Māṇḍūkya Upaniṣad 1</cite>',
  'nada.a.t': '— waken',
  'nada.a.p': 'De eerste klank opent de keel. Het is de wakende wereld: naar buiten gericht, door iedereen gedeeld, gemaakt van dingen.',
  'nada.u.t': '— dromen',
  'nada.u.p': 'De tweede klank rolt naar voren door de mond. Het is de droomwereld: naar binnen gericht, lichtend, gemaakt van geest.',
  'nada.m.t': '— diepe slaap',
  'nada.m.p': 'De derde klank sluit de lippen. Het is droomloze slaap: onverdeeld, in rust, één massa van bewustzijn.',
  'nada.t.t': '— de vierde',
  'nada.t.p': 'Dan de stilte na de klank. Geen toestand, maar de getuige van alle toestanden — vredig, heilzaam, zonder tweede. Dit, zegt de Upaniṣad, is het Zelf.',
  'nada.note': 'Zand op een trillende plaat verzamelt zich waar de plaat stilstaat. Wat je ziet is die natuurkunde, live berekend voor elke korrel.',

  'nas.title': 'Het Scheppingslied',
  'nas.lede': 'Zo’n drieduizend jaar geleden stelde een Vedische dichter de oudste vraag die er is — en had de moed haar open te laten.',
  'nas.v1': 'Toen was er geen niet-zijn en ook geen zijn; geen luchtruim, geen hemel daarboven. Wat bewoog er? Waar? In wiens hoede? Was er water, peilloos diep?',
  'nas.v2': 'Er was toen geen dood, en ook geen onsterfelijkheid; geen teken van nacht of dag. Dat Ene ademde, zonder wind, uit eigen aard. Buiten dat was er helemaal niets.',
  'nas.v3': 'Duisternis was verborgen in duisternis, in het begin; dit alles was vormloos water. Wat aan het ontstaan was, bedekt door de leegte — dat Ene werd geboren door de kracht van hitte.',
  'nas.v4': 'In het begin ontstond er verlangen in — het eerste zaad van de geest. Zoekend in hun hart, met wijsheid, vonden de dichters de band van het zijn in het niet-zijn.',
  'nas.v6': 'Maar wie weet het werkelijk? Wie kan het hier verkondigen — waar het geboren werd, waar deze schepping vandaan kwam? De goden kwamen pas na de schepping van deze wereld. Wie weet dan waar zij ontstond?',
  'nas.v7': 'Waar deze schepping vandaan kwam — of zij zichzelf gevormd heeft, of niet — hij die over haar waakt in de hoogste hemel, hij weet het zeker. Of misschien weet hij het niet.',

  'kala.title': 'Tijd is een wiel',
  'kala.lede': 'Tijd loopt hier niet in een rechte lijn van schepping naar einde. Zij draait — in cycli binnen cycli, van een oogwenk tot de levensduur van de schepper zelf.',
  'kala.s1': 'Een oogwenk. Vijftien oogwenken vormen een kāṣṭhā, dertig kāṣṭhā’s een kalā, dertig kalā’s een muhūrta.',
  'kala.s2': 'Achtenveertig minuten. Dertig muhūrta’s vormen een dag en een nacht — en elk heeft een eigen kwaliteit, gunstig of niet, voor elke onderneming.',
  'kala.s3': 'Een heel mensenjaar is één dag en nacht van de goden. Hun jaar duurt 360 van de onze.',
  'kala.s4': 'Vier tijdperken volgen elkaar op, steeds korter, in de verhouding 4 : 3 : 2 : 1. In het eerste staat Dharma stevig op vier poten, als een stier; met elk tijdperk verliest hij er één.',
  'kala.s5': 'Samen vormen de vier tijdperken een groot tijdperk van 4.320.000 jaar. Eenenzeventig grote tijdperken vormen de heerschappij van één Manu, de vader van de mensheid.',
  'kala.s6': 'Duizend grote tijdperken zijn één dag van Brahmā, de schepper: 4,32 miljard jaar — ongeveer de leeftijd van de aarde. Daarna volgt een even lange nacht, waarin de werelden opgelost rusten.',
  'kala.s7': 'Brahmā leeft honderd jaar van zulke dagen en nachten: 311 biljoen jaar. Dan lost ook hij op — en ontwaakt er een nieuwe Brahmā op een lotus.',
  'kala.s8t': 'En daarbuiten?',
  'kala.s8': 'Talloze universa, zegt de Bhāgavata Purāṇa, zweven als stofjes door de poriën van het Oneindige — elk met een eigen Brahmā, elk draaiend op een eigen wiel.',
  'kala.now': 'Nu, volgens de traditionele telling',
  'kala.kali': 'Kali Yuga, jaar',
  'kala.left': 'jaar resteert in dit tijdperk',
  'kala.sagan': '“Het hindoeïsme is het enige van de grote wereldgeloven dat gewijd is aan het idee dat de kosmos zelf een immens, ja een oneindig aantal doden en wedergeboorten ondergaat. Het is de enige religie waarin de tijdschalen overeenkomen… met die van de moderne wetenschappelijke kosmologie.”',

  'sky.title': 'De hemel, op dit moment',
  'sky.lede': 'Al drieduizend jaar leest de hindoeïstische tijdrekening de klok van de hemel: de Maan die de Zon inhaalt door zevenentwintig maanhuizen, de nakṣatra’s. Deze almanak — de pañcāṅga, “vijf ledematen” — wordt in jouw browser berekend, voor precies dit moment.',
  'sky.note': 'Siderische posities met Lahiri-ayanāṃśa, geocentrisch, voor dit moment. Traditionele almanakken noemen de dag naar de tithi bij plaatselijke zonsopkomst. Sterren: Yale Bright Star Catalogue.',

  'nat.title': 'De dans van Śiva',
  'nat.lede': 'In een ring van vuur danst Śiva als Naṭarāja — Heer van de Dans — het universum tot leven, houdt het in stand en lost het op, in één eindeloze beweging. De dans kent vijf handelingen.',
  'nat.1t': 'schepping',
  'nat.1': 'In zijn rechterbovenhand de ḍamaru: de zandlopervormige trommel. Zijn slag is de eerste hartslag van de tijd — uit klank ontvouwt zich de schepping.',
  'nat.2t': 'instandhouding',
  'nat.2': 'Zijn rechteronderhand is geheven in abhaya mudrā — “vrees niet.” De dans houdt alles in stand wat hij schept.',
  'nat.3t': 'ontbinding',
  'nat.3': 'In zijn linkerbovenhand agni: het vuur dat elke vorm beëindigt, zodat nieuwe vormen kunnen ontstaan. De ring van vlammen is de kosmos zelf, altijd brandend.',
  'nat.4t': 'verhulling',
  'nat.4': 'Zijn rechtervoet drukt Apasmāra neer, de dwerg van onwetendheid — de sluier van vergetelheid die onze ware natuur verbergt.',
  'nat.5t': 'genade',
  'nat.5': 'Zijn linkerhand wijst, als de slurf van een olifant, naar de geheven voet: toevlucht en bevrijding. Vrijheid is binnen handbereik.',
  'nat.6': 'Bij CERN, het Europese laboratorium voor deeltjesfysica, staat een twee meter hoge Naṭarāja — een geschenk van India. Op de plaquette citeert men natuurkundige Fritjof Capra: “Voor de moderne fysici is Śiva’s dans dus de dans van de subatomaire materie.”',

  'yan.title': 'Geometrie van de Godin',
  'yan.lede': 'Negen in elkaar grijpende driehoeken — vier omhoog voor Śiva, zuiver bewustzijn, en vijf omlaag voor Śakti, scheppende energie — weven drieënveertig kleinere driehoeken rond één enkel punt. De Śrī Yantra wordt vereerd als het lichaam van de Godin Tripura Sundarī: de hele kosmos, als geometrie.',
  'yan.1': 'Een vierkant met vier poorten: het aardse vlak, waar de pelgrim binnentreedt. <em>Trailokya-mohana</em> — betoveraar van de drie werelden.',
  'yan.23t': 'Lotussen van 16 en 8 bloembladen',
  'yan.23': 'De vervuller van alle verlangens, en de beroerder van alles — de zintuigen en de geest, naar buiten bloeiend.',
  'yan.4t': 'Veertien driehoeken',
  'yan.4': '<em>Sarva-saubhāgya-dāyaka</em> — schenker van alle voorspoed.',
  'yan.56t': 'Twee ringen van tien',
  'yan.56': 'De volbrenger van alle doelen, en de beschermer van allen.',
  'yan.78t': 'Acht driehoeken, dan één',
  'yan.78': 'De wegnemer van alle kwalen; dan de ene binnenste driehoek, schenker van elke volmaaktheid.',
  'yan.9': 'Het punt zonder afmeting, waar Śiva en Śakti één zijn. <em>Sarvānanda-maya</em> — geheel gemaakt van gelukzaligheid. De reis naar binnen eindigt waar alles begon.',
  'yan.meru': 'Verhef elke omhulling tot de hoogte van haar rang en het diagram wordt een berg: de Mahā Meru, de Śrī Yantra in drie dimensies, gegoten in metaal en vereerd in huizen en tempels. De top is de bindu. Beweeg je cursor om eromheen te lopen.',
  'yan.note': 'Een echte Śrī Yantra tekenen — waarin lijnen elkaar in exacte drievoudige punten ontmoeten — is een werkelijke wiskundige puzzel. Deze wordt numeriek opgelost in je browser, niet overgetrokken.',

  'kol.title': 'Een lijn rond elk punt',
  'kol.lede': 'Elke dageraad vegen vrouwen in heel Tamil Nadu de drempel en tekenen een kolam: één vloeiende lijn van rijstmeel, die zich rond een raster van stippen slingert. Tegen de middag is hij verdwenen — overgelopen, weggewaaid, opgegeten door mieren en vogels. Dat is juist de bedoeling: een dagelijks geschenk van schoonheid, en van voedsel voor de kleinste wezens. Morgen een nieuwe.',
  'kol.body': 'De lussen volgen verborgen regels; wiskundigen bestuderen ze als spiegelkrommen. Deze is zojuist gegenereerd, alleen voor jou.',
  'kol.new': 'Teken een nieuwe kolam',
  'kol.sikku': 'Eén enkele lijn',
  'kol.color': 'Feestkleuren',

  'man.title': 'De tempel is een berg',
  'man.1': 'Het begint als een diagram: een raster van vierenzestig vakken waarop het kosmische wezen ligt, met Brahmā in het midden. De plattegrond van de tempel is een kaart van het universum.',
  'man.2': 'In het hart het “baarmoederhuis”: een kleine, donkere, onversierde kamer waar de godheid woont. Al het andere bestaat om je hierheen te leiden.',
  'man.3': 'Boven de baarmoeder rijst de “piek” — de berg Meru, as van de wereld, de berg in het midden van de kosmos.',
  'man.4t': 'Een fractal in steen',
  'man.4': 'Kleinere pieken scharen zich rond de grote, en nog kleinere rond die. Bij de Kandāriya Mahādeva-tempel in Khajuraho herhalen vierentachtig miniatuurtorens het geheel — hier ook: één, vier, zestien, vierenzestig. Duizend jaar voordat het woord bestond: een fractal.',
  'man.5': 'De pelgrim loopt er met de klok mee omheen en houdt het heilige altijd aan de rechterkant — zoals de Zon langs de hemel lijkt te trekken.',

  'av.title': 'Tien nederdalingen',
  'av.lede': 'Telkens wanneer dharma afneemt, daalt Viṣṇu neer. De tien klassieke avatāra’s volgen een volgorde die velen met evolutie hebben vergeleken: van vis naar amfibie, naar dier, naar mens-dier, naar dwerg, naar de volledige mens — en één die nog moet komen.',
  'av.water': 'water',
  'av.human': 'mens',
  'ek.title': 'Eén waarheid, vele namen',
  'ek.lede': '“De waarheid is één; de wijzen noemen haar met vele namen.” Voor veel hindoes zijn de goden gezichten van één werkelijkheid — Brahman — zoals één licht uiteenvalt in vele kleuren. Kies een licht om een gezicht te ontmoeten.',

  'gita.spin': 'Draai het wiel',
  'gita.title': 'Het lied op het slagveld',
  'gita.lede': 'Tussen twee legers legt een krijger zijn boog neer. Zijn wagenmenner, Kṛṣṇa, beantwoordt zijn wanhoop in zevenhonderd verzen — over handelen, dood en vrijheid. De Gītā heeft achttien hoofdstukken; de oorlog die erop volgt duurde achttien dagen. Draai het wagenwiel om een vers te ontvangen.',

  'pur.1': 'Dat is heel. Dit is heel. Uit het hele ontstaat het hele. Neem het hele weg uit het hele — en het hele blijft.',
  'pur.2': 'Kijk goed: elke bol weerspiegelt elke andere. Elke bol bevat het geheel.',
  'pur.3': 'Dat ben jij.',
  'pur.4': 'Vrede van binnen. Vrede rondom. Vrede daarbuiten.',

  'ret.1': 'Er is geen einde. Alleen terugkeer.',
  'ret.2': 'blijf scrollen — de cyclus begint opnieuw',
  'col.1': 'Sanātana is volledig uit code gemaakt door Claude, een AI van Anthropic: GPU-deeltjesfysica, shaders, gesynthetiseerde tanpura en stem, live astronomie, numeriek opgeloste geometrie. Er staan geen afbeeldingen en geen audiobestanden op deze site.',
  'col.2': 'Sanātana Dharma is een uitgestrekte, levende en veelstemmige traditie. Dit is een kleine, liefdevolle poging om iets van haar schoonheid te tonen — geen volledig of gezaghebbend verslag. Vertalingen uit het Sanskriet zijn vrije weergaven.',
};
